### ISSUE TITLE
Support KSP

### ISSUE THREAD

**Issue by burntcookie90** [ansman/auto-dagger#81]
Dagger just released initial KSP support (https://github.com/google/dagger/releases/tag/dagger-2.48). Unfortunately, upstream processors also need to be KSP compliant.

**Comment by ansman** [comment]
Good thing auto-dagger is already KSP compliant :) 
Just change `kapt` to `ksp` for the auto-dagger compiler and it will work just fine. I just need to update the documentation to mention this.

**Comment by ansman** [comment]
Looks like there are some issues though, namely that auto-dagger generates extension functions for `@Binds` which aren't supported with KSP.
